# Generated by Django 5.0.6 on 2024-07-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headquiz',
            options={'permissions': [('can_view_first1_headquiz', 'Can view the first 1 headquizzes'), ('can_view_all_headquiz', 'Can view all headquizzes')]},
        ),
    ]
